export const LOAD_CUSTOMER_INFO = 'LOAD_CUSTOMER_INFO';
export const LOAD_PORTFOLIO_INFO = 'LOAD_PORTFOLIO_INFO';
export const SET_QUESTION_NUMBER = 'SET_QUESTION_NUMBER';

export const SET_EXPERIENCE = 'SET_EXPERIENCE';
export const SET_KNOWLEDGE = 'SET_KNOWLEDGE';
export const SET_INVESTMENT_HORIZON = 'SET_INVESTMENT_HORIZON';
export const SET_AGE = 'SET_AGE';
export const SET_INITIAL_INVESTMENT = 'SET_INITIAL_INVESTMENT';
export const SET_ASSET_TYPE = 'SET_ASSET_TYPE'

export const CUSTOMER_INFO_SAVE_REQUEST = 'CUSTOMER_INFO_SAVE_REQUEST';
export const CUSTOMER_INFO_SAVE_SUCCESS = 'CUSTOMER_INFO_SAVE_SUCCESS';
export const CUSTOMER_INFO_SAVE_FAILURE = 'CUSTOMER_INFO_SAVE_FAILURE';
