export const LOAD_CUSTOMER_INFO = 'LOAD_CUSTOMER_INFO';
export const LOAD_PORTFOLIO_INFO = 'LOAD_PORTFOLIO_INFO';
export const SET_QUESTION_NUMBER = 'SET_QUESTION_NUMBER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
